# Generated by Django 3.2.13 on 2022-05-27 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('profissional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('status', models.CharField(blank=True, choices=[('A', 'Aberto'), ('T', 'Andamento'), ('F', 'Fechado')], max_length=1, null=True, verbose_name='Status')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Preço')),
                ('pagamento', models.CharField(blank=True, choices=[('D', 'Dinheiro'), ('CD', 'Cartão Débito'), ('CC', 'Cartão Crédito')], max_length=2, null=True, verbose_name='Pagamento')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.person')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profissional.prof')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profissional.service')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agenda',
            },
        ),
    ]
