# Generated by Django 4.0.4 on 2022-07-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_agenda_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
