# Generated by Django 4.0.4 on 2022-07-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_person_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
