# Generated by Django 3.2.13 on 2022-05-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Profissional')),
                ('telefone', models.CharField(blank=True, max_length=9, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissional',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Serviço')),
                ('pagamento', models.CharField(blank=True, choices=[('D', 'Dinheiro'), ('CD', 'Cartão Débito'), ('CC', 'Cartão Crédito')], max_length=2, verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
