# Generated by Django 4.0.4 on 2022-05-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='nome',
            field=models.CharField(choices=[('corte', 'Corte'), ('barba', 'Barba'), ('sobrancelha', 'Sobrancelha'), ('corte_sobrancelha', 'Corte e sobrancelha'), ('corte_barba', 'Corte e barba'), ('barba_sobrancelha', 'Barba e sobrancelha'), ('corte_barba_sobrancelha', 'Corte, barba e sobrancelha')], max_length=100, verbose_name='Serviço'),
        ),
    ]
