# Generated by Django 4.0.4 on 2022-05-30 02:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0003_service_duracao_alter_service_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='preco',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Preço'),
            preserve_default=False,
        ),
    ]
