# Generated by Django 4.0.4 on 2022-05-30 02:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0004_service_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
