# Generated by Django 4.0.4 on 2022-05-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0005_service_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
