# Generated by Django 4.0.4 on 2022-07-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0008_alter_service_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='telefone',
            field=models.CharField(blank=True, max_length=14, verbose_name='Telefone'),
        ),
    ]
