# Generated by Django 4.0.4 on 2022-06-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0008_alter_service_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='preco',
            field=models.FloatField(default=0, verbose_name='Preço R$'),
        ),
    ]
