# Generated by Django 4.0.4 on 2022-06-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0009_alter_service_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prof',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
