# Generated by Django 4.0.4 on 2022-07-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0009_alter_prof_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
