# Generated by Django 4.0.4 on 2022-06-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0011_remove_prof_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
