# Generated by Django 4.0.4 on 2022-06-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0012_alter_prof_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
