# Generated by Django 4.0.4 on 2022-06-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0013_alter_prof_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prof',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
