# Generated by Django 4.0.4 on 2022-06-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0015_remove_prof_created_at_remove_prof_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='telefone',
            field=models.CharField(blank=True, max_length=14, verbose_name='Telefone'),
        ),
    ]
