# Generated by Django 4.0.4 on 2022-06-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0016_alter_prof_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='telefone',
            field=models.CharField(blank=True, max_length=9, verbose_name='Telefone'),
        ),
    ]
