# Generated by Django 4.0.4 on 2022-06-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0017_alter_prof_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duracao',
            field=models.CharField(choices=[('00:30', '00:30'), ('01:00', '01:00'), ('01:30', '01:30'), ('02:00', '02:00')], max_length=50, verbose_name='Duração'),
        ),
    ]
