# Generated by Django 4.0.4 on 2022-06-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0018_alter_service_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duracao',
            field=models.CharField(choices=[('meia_hora', '00:30'), ('uma_hora', '01:00'), ('uma_hora_e_meia', '01:30'), ('duas_horas', '02:00')], max_length=50, verbose_name='Duração'),
        ),
    ]
